https://localhost:8000/api/user

#### API DESTINASI
http://127.0.0.1:8000/api/destinasi


#### API DESTINASI
http://127.0.0.1:8000/api/destinasi/77



#### API PAKET WISATA
http://127.0.0.1:8000/api/paket-wisata